---
version: "3.3"

volumes:
  data:

services:
  logstash:
    image: "docker.elastic.co/logstash/logstash:7.2.0"
    restart: "always"
    ports:
      - "5001:5001/udp"
    volumes:
      - ./pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./pipeline-logs.conf:/usr/share/logstash/pipeline/pipeline-logs.conf
    environment:
      GRAPHITE_HOST: "graphite"
      GRAPHITE_PORT: 2023
      ELASTICSEARCH_HOST: "http://elasticsearch:9200"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.6.2"
    restart: "always"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.6.2"
    restart: "always"
    ports:
      - "8601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
  log-generator:
    image: "mingrammer/flog"
    command: "-d 1 -l"
    volumes:
      - data:/dev/stdout
