---
- hosts: all
  become: true
  become_method: sudo
  vars:
    deploy_user: vagrant
  tasks:
    - debug:
        msg: "Hello {{ inventory_hostname }}"
    - include_role:
        name: docker
    - name: Add vagrant user to docker group
      user:
        append: true
        groups:
          - docker
        name: "{{ deploy_user }}"
    - name: Copy project
      copy:
        src: "apps/{{ inventory_hostname }}/"
        dest: "/srv"
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
